<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{ name: string; section?: 'props' | 'events' | 'slots' }>()

// The api-generator (Batch 10) emits one JSON file per component. We glob them
// eagerly so a missing file degrades gracefully until the generator runs.
const apiModules = import.meta.glob('../api/*.json', { eager: true }) as Record<
  string,
  { default: Record<string, unknown> }
>

const api = computed(() => apiModules[`../api/${props.name}.json`]?.default)
const section = computed(() => props.section ?? 'props')

const rows = computed(() => {
  const data = api.value?.[section.value] as Record<string, Record<string, unknown>> | undefined
  if (!data) return []
  return Object.entries(data).map(([key, meta]) => ({ name: key, ...meta }))
})
</script>

<template>
  <div class="api-table">
    <div v-if="!api" class="api-table__pending">
      API reference for <code>{{ name }}</code> is generated by
      <code>@vue-dl/api-generator</code> (Batch 10). Run
      <code>pnpm --filter @vue-dl/api-generator generate</code>.
    </div>
    <table v-else>
      <thead>
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th>Default</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in rows" :key="row.name">
          <td>
            <code>{{ row.name }}</code>
          </td>
          <td>
            <code>{{ row.type ?? '—' }}</code>
          </td>
          <td>
            <code>{{ row.default ?? '—' }}</code>
          </td>
          <td>{{ row.description ?? '' }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
