<script setup lang="ts">
import { computed, ref } from 'vue'

const props = defineProps<{ name: string }>()

// The api-generator (Batch 10) emits one JSON file per component.
const apiModules = import.meta.glob('../api/*.json', { eager: true }) as Record<
  string,
  { default: ApiData }
>

interface Row {
  type?: string
  default?: string
  description?: string
}
interface ApiData {
  displayName: string
  props?: Record<string, Row>
  events?: Record<string, Row>
  slots?: Record<string, Row>
}

const api = computed(() => apiModules[`../api/${props.name}.json`]?.default)

function entries(section?: Record<string, Row>) {
  return section ? Object.entries(section).sort(([a], [b]) => a.localeCompare(b)) : []
}

const propRows = computed(() => entries(api.value?.props))
const eventRows = computed(() => entries(api.value?.events))
const slotRows = computed(() => entries(api.value?.slots))

const sections = computed(() =>
  [
    { key: 'props', label: 'Props', count: propRows.value.length },
    { key: 'events', label: 'Events', count: eventRows.value.length },
    { key: 'slots', label: 'Slots', count: slotRows.value.length },
  ].filter(s => s.count > 0)
)

const active = ref('props')
const rows = computed(() => {
  if (active.value === 'events') return eventRows.value
  if (active.value === 'slots') return slotRows.value
  return propRows.value
})
const showType = computed(() => active.value === 'props')
const showDefault = computed(() => active.value === 'props')
</script>

<template>
  <div class="api">
    <div v-if="!api" class="api-table__pending">
      API reference for <code>{{ name }}</code> is generated by
      <code>@rukkiecodes/api-generator</code>. Run
      <code>pnpm --filter @rukkiecodes/api-generator generate</code>.
    </div>

    <template v-else>
      <div class="api__tabs">
        <button
          v-for="s in sections"
          :key="s.key"
          class="api__tab"
          :class="{ 'api__tab--active': active === s.key }"
          @click="active = s.key"
        >
          {{ s.label }}
          <span class="api__count">{{ s.count }}</span>
        </button>
      </div>

      <div class="api__table-wrap">
        <table class="api__table">
          <thead>
            <tr>
              <th>Name</th>
              <th v-if="showType">Type</th>
              <th v-if="showDefault">Default</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="[key, row] in rows" :key="key">
              <td>
                <code class="api__name">{{ key }}</code>
              </td>
              <td v-if="showType">
                <code class="api__type">{{ row.type ?? '—' }}</code>
              </td>
              <td v-if="showDefault">
                <code class="api__default">{{ row.default ?? '—' }}</code>
              </td>
              <td class="api__desc">{{ row.description || '—' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>
  </div>
</template>
