export { FTabs, makeVdTabsProps } from './FTabs'
export { FTab, makeVdTabProps } from './FTab'
export { FTabPanel, makeVdTabPanelProps } from './FTabPanel'
export { FTabsWindow, makeVdTabsWindowProps } from './FTabsWindow'
export { FTabsSymbol, FTabsWindowSymbol } from './key'
