export { FTabs, makeFTabsProps } from './FTabs'
export { FTab, makeFTabProps } from './FTab'
export { FTabPanel, makeFTabPanelProps } from './FTabPanel'
export { FTabsWindow, makeFTabsWindowProps } from './FTabsWindow'
export { FTabsSymbol, FTabsWindowSymbol } from './key'
