// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.

import { Activity } from './icons/activity'
import { Airplay } from './icons/airplay'
import { AlertCircle } from './icons/alert-circle'
import { AlertOctagon } from './icons/alert-octagon'
import { AlertTriangle } from './icons/alert-triangle'
import { AlignCenter } from './icons/align-center'
import { AlignJustify } from './icons/align-justify'
import { AlignLeft } from './icons/align-left'
import { AlignRight } from './icons/align-right'
import { Anchor } from './icons/anchor'
import { Aperture } from './icons/aperture'
import { Archive } from './icons/archive'
import { ArrowDownCircle } from './icons/arrow-down-circle'
import { ArrowDownLeft } from './icons/arrow-down-left'
import { ArrowDownRight } from './icons/arrow-down-right'
import { ArrowDown } from './icons/arrow-down'
import { ArrowLeftCircle } from './icons/arrow-left-circle'
import { ArrowLeft } from './icons/arrow-left'
import { ArrowRightCircle } from './icons/arrow-right-circle'
import { ArrowRight } from './icons/arrow-right'
import { ArrowUpCircle } from './icons/arrow-up-circle'
import { ArrowUpLeft } from './icons/arrow-up-left'
import { ArrowUpRight } from './icons/arrow-up-right'
import { ArrowUp } from './icons/arrow-up'
import { AtSign } from './icons/at-sign'
import { Award } from './icons/award'
import { BarChart2 } from './icons/bar-chart-2'
import { BarChart } from './icons/bar-chart'
import { BatteryCharging } from './icons/battery-charging'
import { Battery } from './icons/battery'
import { BellOff } from './icons/bell-off'
import { Bell } from './icons/bell'
import { Bluetooth } from './icons/bluetooth'
import { Bold } from './icons/bold'
import { BookOpen } from './icons/book-open'
import { Book } from './icons/book'
import { Bookmark } from './icons/bookmark'
import { Box } from './icons/box'
import { Briefcase } from './icons/briefcase'
import { Calendar } from './icons/calendar'
import { CameraOff } from './icons/camera-off'
import { Camera } from './icons/camera'
import { Cast } from './icons/cast'
import { CheckCircle } from './icons/check-circle'
import { CheckSquare } from './icons/check-square'
import { Check } from './icons/check'
import { ChevronDown } from './icons/chevron-down'
import { ChevronLeft } from './icons/chevron-left'
import { ChevronRight } from './icons/chevron-right'
import { ChevronUp } from './icons/chevron-up'
import { ChevronsDown } from './icons/chevrons-down'
import { ChevronsLeft } from './icons/chevrons-left'
import { ChevronsRight } from './icons/chevrons-right'
import { ChevronsUp } from './icons/chevrons-up'
import { Chrome } from './icons/chrome'
import { Circle } from './icons/circle'
import { Clipboard } from './icons/clipboard'
import { Clock } from './icons/clock'
import { CloudDrizzle } from './icons/cloud-drizzle'
import { CloudLightning } from './icons/cloud-lightning'
import { CloudOff } from './icons/cloud-off'
import { CloudRain } from './icons/cloud-rain'
import { CloudSnow } from './icons/cloud-snow'
import { Cloud } from './icons/cloud'
import { Code } from './icons/code'
import { Codepen } from './icons/codepen'
import { Codesandbox } from './icons/codesandbox'
import { Coffee } from './icons/coffee'
import { Columns } from './icons/columns'
import { Command } from './icons/command'
import { Compass } from './icons/compass'
import { Copy } from './icons/copy'
import { CornerDownLeft } from './icons/corner-down-left'
import { CornerDownRight } from './icons/corner-down-right'
import { CornerLeftDown } from './icons/corner-left-down'
import { CornerLeftUp } from './icons/corner-left-up'
import { CornerRightDown } from './icons/corner-right-down'
import { CornerRightUp } from './icons/corner-right-up'
import { CornerUpLeft } from './icons/corner-up-left'
import { CornerUpRight } from './icons/corner-up-right'
import { Cpu } from './icons/cpu'
import { CreditCard } from './icons/credit-card'
import { Crop } from './icons/crop'
import { Crosshair } from './icons/crosshair'
import { Database } from './icons/database'
import { Delete } from './icons/delete'
import { Disc } from './icons/disc'
import { DivideCircle } from './icons/divide-circle'
import { DivideSquare } from './icons/divide-square'
import { Divide } from './icons/divide'
import { DollarSign } from './icons/dollar-sign'
import { DownloadCloud } from './icons/download-cloud'
import { Download } from './icons/download'
import { Dribbble } from './icons/dribbble'
import { Droplet } from './icons/droplet'
import { Edit2 } from './icons/edit-2'
import { Edit3 } from './icons/edit-3'
import { Edit } from './icons/edit'
import { ExternalLink } from './icons/external-link'
import { EyeOff } from './icons/eye-off'
import { Eye } from './icons/eye'
import { Facebook } from './icons/facebook'
import { FastForward } from './icons/fast-forward'
import { Feather } from './icons/feather'
import { Figma } from './icons/figma'
import { FileMinus } from './icons/file-minus'
import { FilePlus } from './icons/file-plus'
import { FileText } from './icons/file-text'
import { File } from './icons/file'
import { Film } from './icons/film'
import { Filter } from './icons/filter'
import { Flag } from './icons/flag'
import { FolderMinus } from './icons/folder-minus'
import { FolderPlus } from './icons/folder-plus'
import { Folder } from './icons/folder'
import { Framer } from './icons/framer'
import { Frown } from './icons/frown'
import { Gift } from './icons/gift'
import { GitBranch } from './icons/git-branch'
import { GitCommit } from './icons/git-commit'
import { GitMerge } from './icons/git-merge'
import { GitPullRequest } from './icons/git-pull-request'
import { Github } from './icons/github'
import { Gitlab } from './icons/gitlab'
import { Globe } from './icons/globe'
import { Grid } from './icons/grid'
import { HardDrive } from './icons/hard-drive'
import { Hash } from './icons/hash'
import { Headphones } from './icons/headphones'
import { Heart } from './icons/heart'
import { HelpCircle } from './icons/help-circle'
import { Hexagon } from './icons/hexagon'
import { Home } from './icons/home'
import { Image } from './icons/image'
import { Inbox } from './icons/inbox'
import { Info } from './icons/info'
import { Instagram } from './icons/instagram'
import { Italic } from './icons/italic'
import { Key } from './icons/key'
import { Layers } from './icons/layers'
import { Layout } from './icons/layout'
import { LifeBuoy } from './icons/life-buoy'
import { Link2 } from './icons/link-2'
import { Link } from './icons/link'
import { Linkedin } from './icons/linkedin'
import { List } from './icons/list'
import { Loader } from './icons/loader'
import { Lock } from './icons/lock'
import { LogIn } from './icons/log-in'
import { LogOut } from './icons/log-out'
import { Mail } from './icons/mail'
import { MapPin } from './icons/map-pin'
import { Map } from './icons/map'
import { Maximize2 } from './icons/maximize-2'
import { Maximize } from './icons/maximize'
import { Meh } from './icons/meh'
import { Menu } from './icons/menu'
import { MessageCircle } from './icons/message-circle'
import { MessageSquare } from './icons/message-square'
import { MicOff } from './icons/mic-off'
import { Mic } from './icons/mic'
import { Minimize2 } from './icons/minimize-2'
import { Minimize } from './icons/minimize'
import { MinusCircle } from './icons/minus-circle'
import { MinusSquare } from './icons/minus-square'
import { Minus } from './icons/minus'
import { Monitor } from './icons/monitor'
import { Moon } from './icons/moon'
import { MoreHorizontal } from './icons/more-horizontal'
import { MoreVertical } from './icons/more-vertical'
import { MousePointer } from './icons/mouse-pointer'
import { Move } from './icons/move'
import { Music } from './icons/music'
import { Navigation2 } from './icons/navigation-2'
import { Navigation } from './icons/navigation'
import { Octagon } from './icons/octagon'
import { Package } from './icons/package'
import { Paperclip } from './icons/paperclip'
import { PauseCircle } from './icons/pause-circle'
import { Pause } from './icons/pause'
import { PenTool } from './icons/pen-tool'
import { Percent } from './icons/percent'
import { PhoneCall } from './icons/phone-call'
import { PhoneForwarded } from './icons/phone-forwarded'
import { PhoneIncoming } from './icons/phone-incoming'
import { PhoneMissed } from './icons/phone-missed'
import { PhoneOff } from './icons/phone-off'
import { PhoneOutgoing } from './icons/phone-outgoing'
import { Phone } from './icons/phone'
import { PieChart } from './icons/pie-chart'
import { PlayCircle } from './icons/play-circle'
import { Play } from './icons/play'
import { PlusCircle } from './icons/plus-circle'
import { PlusSquare } from './icons/plus-square'
import { Plus } from './icons/plus'
import { Pocket } from './icons/pocket'
import { Power } from './icons/power'
import { Printer } from './icons/printer'
import { Radio } from './icons/radio'
import { RefreshCcw } from './icons/refresh-ccw'
import { RefreshCw } from './icons/refresh-cw'
import { Repeat } from './icons/repeat'
import { Rewind } from './icons/rewind'
import { RotateCcw } from './icons/rotate-ccw'
import { RotateCw } from './icons/rotate-cw'
import { Rss } from './icons/rss'
import { Save } from './icons/save'
import { Scissors } from './icons/scissors'
import { Search } from './icons/search'
import { Send } from './icons/send'
import { Server } from './icons/server'
import { Settings } from './icons/settings'
import { Share2 } from './icons/share-2'
import { Share } from './icons/share'
import { ShieldOff } from './icons/shield-off'
import { Shield } from './icons/shield'
import { ShoppingBag } from './icons/shopping-bag'
import { ShoppingCart } from './icons/shopping-cart'
import { Shuffle } from './icons/shuffle'
import { Sidebar } from './icons/sidebar'
import { SkipBack } from './icons/skip-back'
import { SkipForward } from './icons/skip-forward'
import { Slack } from './icons/slack'
import { Slash } from './icons/slash'
import { Sliders } from './icons/sliders'
import { Smartphone } from './icons/smartphone'
import { Smile } from './icons/smile'
import { Speaker } from './icons/speaker'
import { Square } from './icons/square'
import { Star } from './icons/star'
import { StopCircle } from './icons/stop-circle'
import { Sun } from './icons/sun'
import { Sunrise } from './icons/sunrise'
import { Sunset } from './icons/sunset'
import { Table } from './icons/table'
import { Tablet } from './icons/tablet'
import { Tag } from './icons/tag'
import { Target } from './icons/target'
import { Terminal } from './icons/terminal'
import { Thermometer } from './icons/thermometer'
import { ThumbsDown } from './icons/thumbs-down'
import { ThumbsUp } from './icons/thumbs-up'
import { ToggleLeft } from './icons/toggle-left'
import { ToggleRight } from './icons/toggle-right'
import { Tool } from './icons/tool'
import { Trash2 } from './icons/trash-2'
import { Trash } from './icons/trash'
import { Trello } from './icons/trello'
import { TrendingDown } from './icons/trending-down'
import { TrendingUp } from './icons/trending-up'
import { Triangle } from './icons/triangle'
import { Truck } from './icons/truck'
import { Tv } from './icons/tv'
import { Twitch } from './icons/twitch'
import { Twitter } from './icons/twitter'
import { Type } from './icons/type'
import { Umbrella } from './icons/umbrella'
import { Underline } from './icons/underline'
import { Unlock } from './icons/unlock'
import { UploadCloud } from './icons/upload-cloud'
import { Upload } from './icons/upload'
import { UserCheck } from './icons/user-check'
import { UserMinus } from './icons/user-minus'
import { UserPlus } from './icons/user-plus'
import { UserX } from './icons/user-x'
import { User } from './icons/user'
import { Users } from './icons/users'
import { VideoOff } from './icons/video-off'
import { Video } from './icons/video'
import { Voicemail } from './icons/voicemail'
import { Volume1 } from './icons/volume-1'
import { Volume2 } from './icons/volume-2'
import { VolumeX } from './icons/volume-x'
import { Volume } from './icons/volume'
import { Watch } from './icons/watch'
import { WifiOff } from './icons/wifi-off'
import { Wifi } from './icons/wifi'
import { Wind } from './icons/wind'
import { XCircle } from './icons/x-circle'
import { XOctagon } from './icons/x-octagon'
import { XSquare } from './icons/x-square'
import { X } from './icons/x'
import { Youtube } from './icons/youtube'
import { ZapOff } from './icons/zap-off'
import { Zap } from './icons/zap'
import { ZoomIn } from './icons/zoom-in'
import { ZoomOut } from './icons/zoom-out'

import type { FeatherIcon } from './runtime'

export const featherIcons: Record<string, FeatherIcon> = {
  'activity': Activity,
  'airplay': Airplay,
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  'align-center': AlignCenter,
  'align-justify': AlignJustify,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  'anchor': Anchor,
  'aperture': Aperture,
  'archive': Archive,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-down': ArrowDown,
  'arrow-left-circle': ArrowLeftCircle,
  'arrow-left': ArrowLeft,
  'arrow-right-circle': ArrowRightCircle,
  'arrow-right': ArrowRight,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-right': ArrowUpRight,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  'award': Award,
  'bar-chart-2': BarChart2,
  'bar-chart': BarChart,
  'battery-charging': BatteryCharging,
  'battery': Battery,
  'bell-off': BellOff,
  'bell': Bell,
  'bluetooth': Bluetooth,
  'bold': Bold,
  'book-open': BookOpen,
  'book': Book,
  'bookmark': Bookmark,
  'box': Box,
  'briefcase': Briefcase,
  'calendar': Calendar,
  'camera-off': CameraOff,
  'camera': Camera,
  'cast': Cast,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'chrome': Chrome,
  'circle': Circle,
  'clipboard': Clipboard,
  'clock': Clock,
  'cloud-drizzle': CloudDrizzle,
  'cloud-lightning': CloudLightning,
  'cloud-off': CloudOff,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud': Cloud,
  'code': Code,
  'codepen': Codepen,
  'codesandbox': Codesandbox,
  'coffee': Coffee,
  'columns': Columns,
  'command': Command,
  'compass': Compass,
  'copy': Copy,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  'corner-left-down': CornerLeftDown,
  'corner-left-up': CornerLeftUp,
  'corner-right-down': CornerRightDown,
  'corner-right-up': CornerRightUp,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'cpu': Cpu,
  'credit-card': CreditCard,
  'crop': Crop,
  'crosshair': Crosshair,
  'database': Database,
  'delete': Delete,
  'disc': Disc,
  'divide-circle': DivideCircle,
  'divide-square': DivideSquare,
  'divide': Divide,
  'dollar-sign': DollarSign,
  'download-cloud': DownloadCloud,
  'download': Download,
  'dribbble': Dribbble,
  'droplet': Droplet,
  'edit-2': Edit2,
  'edit-3': Edit3,
  'edit': Edit,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  'eye': Eye,
  'facebook': Facebook,
  'fast-forward': FastForward,
  'feather': Feather,
  'figma': Figma,
  'file-minus': FileMinus,
  'file-plus': FilePlus,
  'file-text': FileText,
  'file': File,
  'film': Film,
  'filter': Filter,
  'flag': Flag,
  'folder-minus': FolderMinus,
  'folder-plus': FolderPlus,
  'folder': Folder,
  'framer': Framer,
  'frown': Frown,
  'gift': Gift,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'github': Github,
  'gitlab': Gitlab,
  'globe': Globe,
  'grid': Grid,
  'hard-drive': HardDrive,
  'hash': Hash,
  'headphones': Headphones,
  'heart': Heart,
  'help-circle': HelpCircle,
  'hexagon': Hexagon,
  'home': Home,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'instagram': Instagram,
  'italic': Italic,
  'key': Key,
  'layers': Layers,
  'layout': Layout,
  'life-buoy': LifeBuoy,
  'link-2': Link2,
  'link': Link,
  'linkedin': Linkedin,
  'list': List,
  'loader': Loader,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'mail': Mail,
  'map-pin': MapPin,
  'map': Map,
  'maximize-2': Maximize2,
  'maximize': Maximize,
  'meh': Meh,
  'menu': Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'mic-off': MicOff,
  'mic': Mic,
  'minimize-2': Minimize2,
  'minimize': Minimize,
  'minus-circle': MinusCircle,
  'minus-square': MinusSquare,
  'minus': Minus,
  'monitor': Monitor,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'mouse-pointer': MousePointer,
  'move': Move,
  'music': Music,
  'navigation-2': Navigation2,
  'navigation': Navigation,
  'octagon': Octagon,
  'package': Package,
  'paperclip': Paperclip,
  'pause-circle': PauseCircle,
  'pause': Pause,
  'pen-tool': PenTool,
  'percent': Percent,
  'phone-call': PhoneCall,
  'phone-forwarded': PhoneForwarded,
  'phone-incoming': PhoneIncoming,
  'phone-missed': PhoneMissed,
  'phone-off': PhoneOff,
  'phone-outgoing': PhoneOutgoing,
  'phone': Phone,
  'pie-chart': PieChart,
  'play-circle': PlayCircle,
  'play': Play,
  'plus-circle': PlusCircle,
  'plus-square': PlusSquare,
  'plus': Plus,
  'pocket': Pocket,
  'power': Power,
  'printer': Printer,
  'radio': Radio,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'rewind': Rewind,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'rss': Rss,
  'save': Save,
  'scissors': Scissors,
  'search': Search,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'share-2': Share2,
  'share': Share,
  'shield-off': ShieldOff,
  'shield': Shield,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shuffle': Shuffle,
  'sidebar': Sidebar,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'slack': Slack,
  'slash': Slash,
  'sliders': Sliders,
  'smartphone': Smartphone,
  'smile': Smile,
  'speaker': Speaker,
  'square': Square,
  'star': Star,
  'stop-circle': StopCircle,
  'sun': Sun,
  'sunrise': Sunrise,
  'sunset': Sunset,
  'table': Table,
  'tablet': Tablet,
  'tag': Tag,
  'target': Target,
  'terminal': Terminal,
  'thermometer': Thermometer,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  'tool': Tool,
  'trash-2': Trash2,
  'trash': Trash,
  'trello': Trello,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle': Triangle,
  'truck': Truck,
  'tv': Tv,
  'twitch': Twitch,
  'twitter': Twitter,
  'type': Type,
  'umbrella': Umbrella,
  'underline': Underline,
  'unlock': Unlock,
  'upload-cloud': UploadCloud,
  'upload': Upload,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-x': UserX,
  'user': User,
  'users': Users,
  'video-off': VideoOff,
  'video': Video,
  'voicemail': Voicemail,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'volume': Volume,
  'watch': Watch,
  'wifi-off': WifiOff,
  'wifi': Wifi,
  'wind': Wind,
  'x-circle': XCircle,
  'x-octagon': XOctagon,
  'x-square': XSquare,
  'x': X,
  'youtube': Youtube,
  'zap-off': ZapOff,
  'zap': Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
}
