// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.

import { Acorn } from './icons/acorn'
import { Activity } from './icons/activity'
import { Airplay } from './icons/airplay'
import { AlarmClock } from './icons/alarm-clock'
import { Album } from './icons/album'
import { AlertCircle } from './icons/alert-circle'
import { AlertOctagon } from './icons/alert-octagon'
import { AlertTriangle } from './icons/alert-triangle'
import { AlignCenter } from './icons/align-center'
import { AlignJustify } from './icons/align-justify'
import { AlignLeft } from './icons/align-left'
import { AlignRight } from './icons/align-right'
import { Ambulance } from './icons/ambulance'
import { Ampersand } from './icons/ampersand'
import { Anchor } from './icons/anchor'
import { Ant } from './icons/ant'
import { Antenna } from './icons/antenna'
import { Anvil } from './icons/anvil'
import { Aperture } from './icons/aperture'
import { Apple } from './icons/apple'
import { Archive } from './icons/archive'
import { ArrowDownCircle } from './icons/arrow-down-circle'
import { ArrowDownLeft } from './icons/arrow-down-left'
import { ArrowDownRight } from './icons/arrow-down-right'
import { ArrowDown } from './icons/arrow-down'
import { ArrowLeftCircle } from './icons/arrow-left-circle'
import { ArrowLeft } from './icons/arrow-left'
import { ArrowRightCircle } from './icons/arrow-right-circle'
import { ArrowRight } from './icons/arrow-right'
import { ArrowUpCircle } from './icons/arrow-up-circle'
import { ArrowUpLeft } from './icons/arrow-up-left'
import { ArrowUpRight } from './icons/arrow-up-right'
import { ArrowUp } from './icons/arrow-up'
import { Asterisk } from './icons/asterisk'
import { AtSign } from './icons/at-sign'
import { Avatar } from './icons/avatar'
import { Avocado } from './icons/avocado'
import { Award } from './icons/award'
import { Axe } from './icons/axe'
import { Baby } from './icons/baby'
import { Backpack } from './icons/backpack'
import { Bacteria } from './icons/bacteria'
import { Banana } from './icons/banana'
import { Bandage } from './icons/bandage'
import { Bank } from './icons/bank'
import { Banknote } from './icons/banknote'
import { BarChart2 } from './icons/bar-chart-2'
import { BarChart } from './icons/bar-chart'
import { Barbell } from './icons/barbell'
import { Barcode } from './icons/barcode'
import { Barn } from './icons/barn'
import { Baseball } from './icons/baseball'
import { Basket } from './icons/basket'
import { Basketball } from './icons/basketball'
import { BatteryCharging } from './icons/battery-charging'
import { Battery } from './icons/battery'
import { Beaker } from './icons/beaker'
import { Bear } from './icons/bear'
import { Bee } from './icons/bee'
import { Beer } from './icons/beer'
import { BellOff } from './icons/bell-off'
import { Bell } from './icons/bell'
import { Belt } from './icons/belt'
import { Bike } from './icons/bike'
import { Biohazard } from './icons/biohazard'
import { Bird } from './icons/bird'
import { Bitcoin } from './icons/bitcoin'
import { BloodDrop } from './icons/blood-drop'
import { Bluetooth } from './icons/bluetooth'
import { Boat } from './icons/boat'
import { Bold } from './icons/bold'
import { Bolt } from './icons/bolt'
import { Bone } from './icons/bone'
import { BookOpen } from './icons/book-open'
import { Book } from './icons/book'
import { Bookmark } from './icons/bookmark'
import { Boot } from './icons/boot'
import { BowTie } from './icons/bow-tie'
import { Bowl } from './icons/bowl'
import { Bowling } from './icons/bowling'
import { Box } from './icons/box'
import { BoxingGlove } from './icons/boxing-glove'
import { Bracelet } from './icons/bracelet'
import { Brain } from './icons/brain'
import { Bread } from './icons/bread'
import { Bridge } from './icons/bridge'
import { Briefcase } from './icons/briefcase'
import { Broccoli } from './icons/broccoli'
import { Broom } from './icons/broom'
import { Bucket } from './icons/bucket'
import { Building } from './icons/building'
import { Bus } from './icons/bus'
import { Butterfly } from './icons/butterfly'
import { Button } from './icons/button'
import { Cabin } from './icons/cabin'
import { Cable } from './icons/cable'
import { Cactus } from './icons/cactus'
import { Cake } from './icons/cake'
import { Calculator } from './icons/calculator'
import { Calendar } from './icons/calendar'
import { CameraOff } from './icons/camera-off'
import { Camera } from './icons/camera'
import { Candle } from './icons/candle'
import { CandlestickChart } from './icons/candlestick-chart'
import { Candy } from './icons/candy'
import { Cap } from './icons/cap'
import { Capsule } from './icons/capsule'
import { Car } from './icons/car'
import { Carrot } from './icons/carrot'
import { Cassette } from './icons/cassette'
import { Cast } from './icons/cast'
import { Castle } from './icons/castle'
import { Cat } from './icons/cat'
import { Caution } from './icons/caution'
import { Cctv } from './icons/cctv'
import { Certificate } from './icons/certificate'
import { Chain } from './icons/chain'
import { Chair } from './icons/chair'
import { Chandelier } from './icons/chandelier'
import { CheckCircle } from './icons/check-circle'
import { CheckSquare } from './icons/check-square'
import { Check } from './icons/check'
import { Cheese } from './icons/cheese'
import { Cherry } from './icons/cherry'
import { Chess } from './icons/chess'
import { ChevronDown } from './icons/chevron-down'
import { ChevronLeft } from './icons/chevron-left'
import { ChevronRight } from './icons/chevron-right'
import { ChevronUp } from './icons/chevron-up'
import { ChevronsDown } from './icons/chevrons-down'
import { ChevronsLeft } from './icons/chevrons-left'
import { ChevronsRight } from './icons/chevrons-right'
import { ChevronsUp } from './icons/chevrons-up'
import { Chrome } from './icons/chrome'
import { Church } from './icons/church'
import { Circle } from './icons/circle'
import { Clap } from './icons/clap'
import { Clapperboard } from './icons/clapperboard'
import { ClipboardCheck } from './icons/clipboard-check'
import { ClipboardList } from './icons/clipboard-list'
import { Clipboard } from './icons/clipboard'
import { Clock } from './icons/clock'
import { CloudDrizzle } from './icons/cloud-drizzle'
import { CloudLightning } from './icons/cloud-lightning'
import { CloudOff } from './icons/cloud-off'
import { CloudRain } from './icons/cloud-rain'
import { CloudSnow } from './icons/cloud-snow'
import { Cloud } from './icons/cloud'
import { Clover } from './icons/clover'
import { Cocktail } from './icons/cocktail'
import { Code } from './icons/code'
import { Codepen } from './icons/codepen'
import { Codesandbox } from './icons/codesandbox'
import { Coffee } from './icons/coffee'
import { Coin } from './icons/coin'
import { Coins } from './icons/coins'
import { Columns } from './icons/columns'
import { Comet } from './icons/comet'
import { Command } from './icons/command'
import { Compass } from './icons/compass'
import { Cone } from './icons/cone'
import { Cookie } from './icons/cookie'
import { Copy } from './icons/copy'
import { Copyright } from './icons/copyright'
import { Corn } from './icons/corn'
import { CornerDownLeft } from './icons/corner-down-left'
import { CornerDownRight } from './icons/corner-down-right'
import { CornerLeftDown } from './icons/corner-left-down'
import { CornerLeftUp } from './icons/corner-left-up'
import { CornerRightDown } from './icons/corner-right-down'
import { CornerRightUp } from './icons/corner-right-up'
import { CornerUpLeft } from './icons/corner-up-left'
import { CornerUpRight } from './icons/corner-up-right'
import { Coupon } from './icons/coupon'
import { Cow } from './icons/cow'
import { Cpu } from './icons/cpu'
import { Crab } from './icons/crab'
import { CreditCard } from './icons/credit-card'
import { Croissant } from './icons/croissant'
import { Crop } from './icons/crop'
import { Cross } from './icons/cross'
import { Crosshair } from './icons/crosshair'
import { Crowd } from './icons/crowd'
import { Crown } from './icons/crown'
import { Crutch } from './icons/crutch'
import { Cube } from './icons/cube'
import { Cupcake } from './icons/cupcake'
import { Cylinder } from './icons/cylinder'
import { Dartboard } from './icons/dartboard'
import { Database } from './icons/database'
import { Deer } from './icons/deer'
import { Delete } from './icons/delete'
import { Desk } from './icons/desk'
import { Detective } from './icons/detective'
import { Dewdrop } from './icons/dewdrop'
import { Diamond } from './icons/diamond'
import { Dice } from './icons/dice'
import { Dinosaur } from './icons/dinosaur'
import { Disc } from './icons/disc'
import { DivideCircle } from './icons/divide-circle'
import { DivideSquare } from './icons/divide-square'
import { Divide } from './icons/divide'
import { Dna } from './icons/dna'
import { Dog } from './icons/dog'
import { DollarSign } from './icons/dollar-sign'
import { Dolphin } from './icons/dolphin'
import { Donut } from './icons/donut'
import { DoorOpen } from './icons/door-open'
import { Door } from './icons/door'
import { Dove } from './icons/dove'
import { DownloadCloud } from './icons/download-cloud'
import { Download } from './icons/download'
import { Dragon } from './icons/dragon'
import { Dress } from './icons/dress'
import { Dribbble } from './icons/dribbble'
import { Drill } from './icons/drill'
import { Droplet } from './icons/droplet'
import { Drum } from './icons/drum'
import { Dumbbell } from './icons/dumbbell'
import { Ear } from './icons/ear'
import { Edit2 } from './icons/edit-2'
import { Edit3 } from './icons/edit-3'
import { Edit } from './icons/edit'
import { Egg } from './icons/egg'
import { Eggplant } from './icons/eggplant'
import { Elephant } from './icons/elephant'
import { Elevator } from './icons/elevator'
import { EnvelopeOpen } from './icons/envelope-open'
import { Envelope } from './icons/envelope'
import { Equalizer } from './icons/equalizer'
import { Eraser } from './icons/eraser'
import { Euro } from './icons/euro'
import { ExternalLink } from './icons/external-link'
import { EyeOff } from './icons/eye-off'
import { Eye } from './icons/eye'
import { Facebook } from './icons/facebook'
import { Factory } from './icons/factory'
import { Family } from './icons/family'
import { Fan } from './icons/fan'
import { FastForward } from './icons/fast-forward'
import { Fax } from './icons/fax'
import { Feather } from './icons/feather'
import { Fence } from './icons/fence'
import { FerrisWheel } from './icons/ferris-wheel'
import { Figma } from './icons/figma'
import { FileMinus } from './icons/file-minus'
import { FilePlus } from './icons/file-plus'
import { FileText } from './icons/file-text'
import { File } from './icons/file'
import { Film } from './icons/film'
import { Filter } from './icons/filter'
import { Fingerprint } from './icons/fingerprint'
import { FireTruck } from './icons/fire-truck'
import { Fire } from './icons/fire'
import { Fireplace } from './icons/fireplace'
import { Firewall } from './icons/firewall'
import { FirstAid } from './icons/first-aid'
import { Fish } from './icons/fish'
import { Fist } from './icons/fist'
import { Flag } from './icons/flag'
import { Flame } from './icons/flame'
import { Flashlight } from './icons/flashlight'
import { Flask } from './icons/flask'
import { FloppyDisk } from './icons/floppy-disk'
import { Flower } from './icons/flower'
import { Flute } from './icons/flute'
import { Fog } from './icons/fog'
import { FolderMinus } from './icons/folder-minus'
import { FolderPlus } from './icons/folder-plus'
import { Folder } from './icons/folder'
import { Football } from './icons/football'
import { Footprint } from './icons/footprint'
import { Fork } from './icons/fork'
import { Fountain } from './icons/fountain'
import { Fox } from './icons/fox'
import { Framer } from './icons/framer'
import { Fries } from './icons/fries'
import { Frog } from './icons/frog'
import { Frown } from './icons/frown'
import { Fuel } from './icons/fuel'
import { Galaxy } from './icons/galaxy'
import { Gamepad } from './icons/gamepad'
import { Garage } from './icons/garage'
import { GasPump } from './icons/gas-pump'
import { Gate } from './icons/gate'
import { Gear } from './icons/gear'
import { Gem } from './icons/gem'
import { GiftCard } from './icons/gift-card'
import { Gift } from './icons/gift'
import { GitBranch } from './icons/git-branch'
import { GitCommit } from './icons/git-commit'
import { GitMerge } from './icons/git-merge'
import { GitPullRequest } from './icons/git-pull-request'
import { Github } from './icons/github'
import { Gitlab } from './icons/gitlab'
import { Glasses } from './icons/glasses'
import { Globe } from './icons/globe'
import { Glove } from './icons/glove'
import { Golf } from './icons/golf'
import { Grape } from './icons/grape'
import { Grid } from './icons/grid'
import { Guitar } from './icons/guitar'
import { Hamburger } from './icons/hamburger'
import { Hammer } from './icons/hammer'
import { Hand } from './icons/hand'
import { Handbag } from './icons/handbag'
import { Handshake } from './icons/handshake'
import { HardDrive } from './icons/hard-drive'
import { Hash } from './icons/hash'
import { Hat } from './icons/hat'
import { Haze } from './icons/haze'
import { Headphones } from './icons/headphones'
import { Headset } from './icons/headset'
import { HeartPulse } from './icons/heart-pulse'
import { Heart } from './icons/heart'
import { Helicopter } from './icons/helicopter'
import { Helmet } from './icons/helmet'
import { HelpCircle } from './icons/help-circle'
import { Heptagon } from './icons/heptagon'
import { Hexagon } from './icons/hexagon'
import { Highlighter } from './icons/highlighter'
import { Hockey } from './icons/hockey'
import { Home } from './icons/home'
import { Hoodie } from './icons/hoodie'
import { Horse } from './icons/horse'
import { Hospital } from './icons/hospital'
import { HotAirBalloon } from './icons/hot-air-balloon'
import { Hotdog } from './icons/hotdog'
import { Hotel } from './icons/hotel'
import { Hourglass } from './icons/hourglass'
import { House } from './icons/house'
import { IceCream } from './icons/ice-cream'
import { Icicle } from './icons/icicle'
import { IdCard } from './icons/id-card'
import { Igloo } from './icons/igloo'
import { Image } from './icons/image'
import { Inbox } from './icons/inbox'
import { Incognito } from './icons/incognito'
import { Infinity } from './icons/infinity'
import { Info } from './icons/info'
import { Instagram } from './icons/instagram'
import { Invoice } from './icons/invoice'
import { Iron } from './icons/iron'
import { Italic } from './icons/italic'
import { Jacket } from './icons/jacket'
import { Jersey } from './icons/jersey'
import { Joystick } from './icons/joystick'
import { Juice } from './icons/juice'
import { Kettlebell } from './icons/kettlebell'
import { Key } from './icons/key'
import { Keyboard } from './icons/keyboard'
import { Keyhole } from './icons/keyhole'
import { Knife } from './icons/knife'
import { Ladder } from './icons/ladder'
import { Ladybug } from './icons/ladybug'
import { Lamp } from './icons/lamp'
import { Lantern } from './icons/lantern'
import { Layers } from './icons/layers'
import { Layout } from './icons/layout'
import { Leaf } from './icons/leaf'
import { Lemon } from './icons/lemon'
import { Library } from './icons/library'
import { LifeBuoy } from './icons/life-buoy'
import { Lightbulb } from './icons/lightbulb'
import { Lighthouse } from './icons/lighthouse'
import { Link2 } from './icons/link-2'
import { Link } from './icons/link'
import { Linkedin } from './icons/linkedin'
import { Lion } from './icons/lion'
import { Lips } from './icons/lips'
import { List } from './icons/list'
import { Loader } from './icons/loader'
import { Lock } from './icons/lock'
import { LogIn } from './icons/log-in'
import { LogOut } from './icons/log-out'
import { Lollipop } from './icons/lollipop'
import { Lungs } from './icons/lungs'
import { Magnet } from './icons/magnet'
import { Mail } from './icons/mail'
import { Mailbox } from './icons/mailbox'
import { MapPin } from './icons/map-pin'
import { Map } from './icons/map'
import { MapleLeaf } from './icons/maple-leaf'
import { Marker } from './icons/marker'
import { Mask } from './icons/mask'
import { Maximize2 } from './icons/maximize-2'
import { Maximize } from './icons/maximize'
import { Medal } from './icons/medal'
import { Meh } from './icons/meh'
import { Menu } from './icons/menu'
import { MessageCircle } from './icons/message-circle'
import { MessageSquare } from './icons/message-square'
import { Meteor } from './icons/meteor'
import { Metronome } from './icons/metronome'
import { MicOff } from './icons/mic-off'
import { Mic } from './icons/mic'
import { Microchip } from './icons/microchip'
import { MicrophoneStage } from './icons/microphone-stage'
import { Microscope } from './icons/microscope'
import { Microwave } from './icons/microwave'
import { Milk } from './icons/milk'
import { Minimize2 } from './icons/minimize-2'
import { Minimize } from './icons/minimize'
import { MinusCircle } from './icons/minus-circle'
import { MinusSquare } from './icons/minus-square'
import { Minus } from './icons/minus'
import { Mirror } from './icons/mirror'
import { Modem } from './icons/modem'
import { Monitor } from './icons/monitor'
import { Monkey } from './icons/monkey'
import { Moon } from './icons/moon'
import { MoreHorizontal } from './icons/more-horizontal'
import { MoreVertical } from './icons/more-vertical'
import { Mosque } from './icons/mosque'
import { Motorcycle } from './icons/motorcycle'
import { Mountain } from './icons/mountain'
import { MousePointer } from './icons/mouse-pointer'
import { Move } from './icons/move'
import { Mug } from './icons/mug'
import { Museum } from './icons/museum'
import { Mushroom } from './icons/mushroom'
import { MusicNote } from './icons/music-note'
import { Music } from './icons/music'
import { Nail } from './icons/nail'
import { Navigation2 } from './icons/navigation-2'
import { Navigation } from './icons/navigation'
import { Necklace } from './icons/necklace'
import { NoEntry } from './icons/no-entry'
import { Nose } from './icons/nose'
import { Notebook } from './icons/notebook'
import { Notepad } from './icons/notepad'
import { Octagon } from './icons/octagon'
import { Octopus } from './icons/octopus'
import { Omega } from './icons/omega'
import { Oval } from './icons/oval'
import { Oven } from './icons/oven'
import { Owl } from './icons/owl'
import { Package } from './icons/package'
import { Padlock } from './icons/padlock'
import { PaintBucket } from './icons/paint-bucket'
import { PaintRoller } from './icons/paint-roller'
import { Paintbrush } from './icons/paintbrush'
import { PalmTree } from './icons/palm-tree'
import { Panda } from './icons/panda'
import { Pants } from './icons/pants'
import { Paperclip } from './icons/paperclip'
import { Parachute } from './icons/parachute'
import { Paragraph } from './icons/paragraph'
import { Parking } from './icons/parking'
import { PauseCircle } from './icons/pause-circle'
import { Pause } from './icons/pause'
import { Paw } from './icons/paw'
import { PeaceSign } from './icons/peace-sign'
import { PenTool } from './icons/pen-tool'
import { Pen } from './icons/pen'
import { Pencil } from './icons/pencil'
import { Penguin } from './icons/penguin'
import { Pentagon } from './icons/pentagon'
import { Pepper } from './icons/pepper'
import { Percent } from './icons/percent'
import { Person } from './icons/person'
import { PhoneCall } from './icons/phone-call'
import { PhoneForwarded } from './icons/phone-forwarded'
import { PhoneIncoming } from './icons/phone-incoming'
import { PhoneMissed } from './icons/phone-missed'
import { PhoneOff } from './icons/phone-off'
import { PhoneOutgoing } from './icons/phone-outgoing'
import { Phone } from './icons/phone'
import { Pi } from './icons/pi'
import { Piano } from './icons/piano'
import { PieChart } from './icons/pie-chart'
import { Pig } from './icons/pig'
import { PiggyBank } from './icons/piggy-bank'
import { Pill } from './icons/pill'
import { Pineapple } from './icons/pineapple'
import { Pinecone } from './icons/pinecone'
import { Pizza } from './icons/pizza'
import { Plane } from './icons/plane'
import { Planet } from './icons/planet'
import { Plate } from './icons/plate'
import { PlayCircle } from './icons/play-circle'
import { Play } from './icons/play'
import { Playlist } from './icons/playlist'
import { Pliers } from './icons/pliers'
import { Plug } from './icons/plug'
import { PlusCircle } from './icons/plus-circle'
import { PlusSquare } from './icons/plus-square'
import { Plus } from './icons/plus'
import { Pocket } from './icons/pocket'
import { Podium } from './icons/podium'
import { Popcorn } from './icons/popcorn'
import { Pound } from './icons/pound'
import { Power } from './icons/power'
import { Presentation } from './icons/presentation'
import { Pretzel } from './icons/pretzel'
import { PriceTag } from './icons/price-tag'
import { Printer } from './icons/printer'
import { Profile } from './icons/profile'
import { Prohibited } from './icons/prohibited'
import { Projector } from './icons/projector'
import { Pushpin } from './icons/pushpin'
import { Puzzle } from './icons/puzzle'
import { Pyramid } from './icons/pyramid'
import { QrCode } from './icons/qr-code'
import { Rabbit } from './icons/rabbit'
import { Radar } from './icons/radar'
import { Radiation } from './icons/radiation'
import { Radio } from './icons/radio'
import { Rainbow } from './icons/rainbow'
import { Rake } from './icons/rake'
import { Receipt } from './icons/receipt'
import { Recycle } from './icons/recycle'
import { RefreshCcw } from './icons/refresh-ccw'
import { RefreshCw } from './icons/refresh-cw'
import { Refrigerator } from './icons/refrigerator'
import { Registered } from './icons/registered'
import { RemoteControl } from './icons/remote-control'
import { Repeat } from './icons/repeat'
import { Rewind } from './icons/rewind'
import { Rhombus } from './icons/rhombus'
import { Ribbon } from './icons/ribbon'
import { Ring } from './icons/ring'
import { Road } from './icons/road'
import { Rocket } from './icons/rocket'
import { Rope } from './icons/rope'
import { Rose } from './icons/rose'
import { RotateCcw } from './icons/rotate-ccw'
import { RotateCw } from './icons/rotate-cw'
import { Router } from './icons/router'
import { Rss } from './icons/rss'
import { Ruler } from './icons/ruler'
import { Rupee } from './icons/rupee'
import { Safe } from './icons/safe'
import { Sailboat } from './icons/sailboat'
import { Sandal } from './icons/sandal'
import { Sandwich } from './icons/sandwich'
import { SatelliteDish } from './icons/satellite-dish'
import { Satellite } from './icons/satellite'
import { Saturn } from './icons/saturn'
import { Save } from './icons/save'
import { Saw } from './icons/saw'
import { Saxophone } from './icons/saxophone'
import { ScaleBalance } from './icons/scale-balance'
import { Scanner } from './icons/scanner'
import { Scarf } from './icons/scarf'
import { School } from './icons/school'
import { Scissors } from './icons/scissors'
import { Scooter } from './icons/scooter'
import { Screw } from './icons/screw'
import { Screwdriver } from './icons/screwdriver'
import { SdCard } from './icons/sd-card'
import { Search } from './icons/search'
import { Seedling } from './icons/seedling'
import { Send } from './icons/send'
import { Server } from './icons/server'
import { Settings } from './icons/settings'
import { Share2 } from './icons/share-2'
import { Share } from './icons/share'
import { Sheep } from './icons/sheep'
import { ShieldOff } from './icons/shield-off'
import { Shield } from './icons/shield'
import { Ship } from './icons/ship'
import { Shirt } from './icons/shirt'
import { Shoe } from './icons/shoe'
import { ShootingStar } from './icons/shooting-star'
import { ShoppingBag } from './icons/shopping-bag'
import { ShoppingCart } from './icons/shopping-cart'
import { Shovel } from './icons/shovel'
import { Shrimp } from './icons/shrimp'
import { Shuffle } from './icons/shuffle'
import { Sidebar } from './icons/sidebar'
import { Sigma } from './icons/sigma'
import { SimCard } from './icons/sim-card'
import { Siren } from './icons/siren'
import { Skateboard } from './icons/skateboard'
import { Skiing } from './icons/skiing'
import { SkipBack } from './icons/skip-back'
import { SkipForward } from './icons/skip-forward'
import { Skyscraper } from './icons/skyscraper'
import { Slack } from './icons/slack'
import { Slash } from './icons/slash'
import { Sliders } from './icons/sliders'
import { Smartphone } from './icons/smartphone'
import { Smile } from './icons/smile'
import { Snail } from './icons/snail'
import { Sneaker } from './icons/sneaker'
import { Snowflake } from './icons/snowflake'
import { Sock } from './icons/sock'
import { Socket } from './icons/socket'
import { Soda } from './icons/soda'
import { Speaker } from './icons/speaker'
import { Sphere } from './icons/sphere'
import { Spider } from './icons/spider'
import { Spiral } from './icons/spiral'
import { Spoon } from './icons/spoon'
import { SprayCan } from './icons/spray-can'
import { Sprout } from './icons/sprout'
import { Square } from './icons/square'
import { Stadium } from './icons/stadium'
import { Stairs } from './icons/stairs'
import { Stamp } from './icons/stamp'
import { Stapler } from './icons/stapler'
import { Star } from './icons/star'
import { Stethoscope } from './icons/stethoscope'
import { StickyNote } from './icons/sticky-note'
import { StopCircle } from './icons/stop-circle'
import { Stopwatch } from './icons/stopwatch'
import { Store } from './icons/store'
import { Stove } from './icons/stove'
import { Strawberry } from './icons/strawberry'
import { Stroller } from './icons/stroller'
import { Submarine } from './icons/submarine'
import { Suitcase } from './icons/suitcase'
import { Sun } from './icons/sun'
import { Sunflower } from './icons/sunflower'
import { Sunglasses } from './icons/sunglasses'
import { Sunrise } from './icons/sunrise'
import { Sunset } from './icons/sunset'
import { Surfing } from './icons/surfing'
import { Swimming } from './icons/swimming'
import { Syringe } from './icons/syringe'
import { TShirt } from './icons/t-shirt'
import { Table } from './icons/table'
import { Tablet } from './icons/tablet'
import { Tag } from './icons/tag'
import { Target } from './icons/target'
import { Taxi } from './icons/taxi'
import { Tea } from './icons/tea'
import { Teapot } from './icons/teapot'
import { Tennis } from './icons/tennis'
import { Tent } from './icons/tent'
import { Terminal } from './icons/terminal'
import { TestTube } from './icons/test-tube'
import { TheaterMasks } from './icons/theater-masks'
import { Thermometer } from './icons/thermometer'
import { Thermostat } from './icons/thermostat'
import { ThumbsDown } from './icons/thumbs-down'
import { ThumbsUp } from './icons/thumbs-up'
import { Ticket } from './icons/ticket'
import { Tie } from './icons/tie'
import { Tiger } from './icons/tiger'
import { Timer } from './icons/timer'
import { ToggleLeft } from './icons/toggle-left'
import { ToggleRight } from './icons/toggle-right'
import { Tomato } from './icons/tomato'
import { Tool } from './icons/tool'
import { Toolbox } from './icons/toolbox'
import { Tooth } from './icons/tooth'
import { Toothbrush } from './icons/toothbrush'
import { Tornado } from './icons/tornado'
import { Tractor } from './icons/tractor'
import { Trademark } from './icons/trademark'
import { TrafficCone } from './icons/traffic-cone'
import { TrafficLight } from './icons/traffic-light'
import { Trailer } from './icons/trailer'
import { Train } from './icons/train'
import { Tram } from './icons/tram'
import { Trash2 } from './icons/trash-2'
import { Trash } from './icons/trash'
import { Treadmill } from './icons/treadmill'
import { TreeEvergreen } from './icons/tree-evergreen'
import { Tree } from './icons/tree'
import { Trello } from './icons/trello'
import { TrendingDown } from './icons/trending-down'
import { TrendingUp } from './icons/trending-up'
import { Triangle } from './icons/triangle'
import { Trophy } from './icons/trophy'
import { Truck } from './icons/truck'
import { Trumpet } from './icons/trumpet'
import { Tulip } from './icons/tulip'
import { Turtle } from './icons/turtle'
import { Tv } from './icons/tv'
import { Twitch } from './icons/twitch'
import { Twitter } from './icons/twitter'
import { Type } from './icons/type'
import { Umbrella } from './icons/umbrella'
import { Underline } from './icons/underline'
import { Unicorn } from './icons/unicorn'
import { Unlock } from './icons/unlock'
import { UploadCloud } from './icons/upload-cloud'
import { Upload } from './icons/upload'
import { Usb } from './icons/usb'
import { UserCheck } from './icons/user-check'
import { UserMinus } from './icons/user-minus'
import { UserPlus } from './icons/user-plus'
import { UserX } from './icons/user-x'
import { User } from './icons/user'
import { Users } from './icons/users'
import { Vacuum } from './icons/vacuum'
import { Van } from './icons/van'
import { Vault } from './icons/vault'
import { Verified } from './icons/verified'
import { VideoOff } from './icons/video-off'
import { Video } from './icons/video'
import { Vinyl } from './icons/vinyl'
import { Violin } from './icons/violin'
import { Virus } from './icons/virus'
import { Voicemail } from './icons/voicemail'
import { Volcano } from './icons/volcano'
import { Volleyball } from './icons/volleyball'
import { Volume1 } from './icons/volume-1'
import { Volume2 } from './icons/volume-2'
import { VolumeX } from './icons/volume-x'
import { Volume } from './icons/volume'
import { Wallet } from './icons/wallet'
import { Warehouse } from './icons/warehouse'
import { WarningTriangle } from './icons/warning-triangle'
import { WashingMachine } from './icons/washing-machine'
import { Watch } from './icons/watch'
import { Watermelon } from './icons/watermelon'
import { Waves } from './icons/waves'
import { Webcam } from './icons/webcam'
import { Whale } from './icons/whale'
import { Wheat } from './icons/wheat'
import { Wheelchair } from './icons/wheelchair'
import { Whistle } from './icons/whistle'
import { Whiteboard } from './icons/whiteboard'
import { WifiOff } from './icons/wifi-off'
import { Wifi } from './icons/wifi'
import { Wind } from './icons/wind'
import { Windmill } from './icons/windmill'
import { Wine } from './icons/wine'
import { Wolf } from './icons/wolf'
import { Worm } from './icons/worm'
import { Wrench } from './icons/wrench'
import { XCircle } from './icons/x-circle'
import { XOctagon } from './icons/x-octagon'
import { XRay } from './icons/x-ray'
import { XSquare } from './icons/x-square'
import { X } from './icons/x'
import { Yen } from './icons/yen'
import { Yoga } from './icons/yoga'
import { Youtube } from './icons/youtube'
import { ZapOff } from './icons/zap-off'
import { Zap } from './icons/zap'
import { ZoomIn } from './icons/zoom-in'
import { ZoomOut } from './icons/zoom-out'

import type { FeatherIcon } from './runtime'

export const featherIcons: Record<string, FeatherIcon> = {
  'acorn': Acorn,
  'activity': Activity,
  'airplay': Airplay,
  'alarm-clock': AlarmClock,
  'album': Album,
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  'align-center': AlignCenter,
  'align-justify': AlignJustify,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  'ambulance': Ambulance,
  'ampersand': Ampersand,
  'anchor': Anchor,
  'ant': Ant,
  'antenna': Antenna,
  'anvil': Anvil,
  'aperture': Aperture,
  'apple': Apple,
  'archive': Archive,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-down': ArrowDown,
  'arrow-left-circle': ArrowLeftCircle,
  'arrow-left': ArrowLeft,
  'arrow-right-circle': ArrowRightCircle,
  'arrow-right': ArrowRight,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-right': ArrowUpRight,
  'arrow-up': ArrowUp,
  'asterisk': Asterisk,
  'at-sign': AtSign,
  'avatar': Avatar,
  'avocado': Avocado,
  'award': Award,
  'axe': Axe,
  'baby': Baby,
  'backpack': Backpack,
  'bacteria': Bacteria,
  'banana': Banana,
  'bandage': Bandage,
  'bank': Bank,
  'banknote': Banknote,
  'bar-chart-2': BarChart2,
  'bar-chart': BarChart,
  'barbell': Barbell,
  'barcode': Barcode,
  'barn': Barn,
  'baseball': Baseball,
  'basket': Basket,
  'basketball': Basketball,
  'battery-charging': BatteryCharging,
  'battery': Battery,
  'beaker': Beaker,
  'bear': Bear,
  'bee': Bee,
  'beer': Beer,
  'bell-off': BellOff,
  'bell': Bell,
  'belt': Belt,
  'bike': Bike,
  'biohazard': Biohazard,
  'bird': Bird,
  'bitcoin': Bitcoin,
  'blood-drop': BloodDrop,
  'bluetooth': Bluetooth,
  'boat': Boat,
  'bold': Bold,
  'bolt': Bolt,
  'bone': Bone,
  'book-open': BookOpen,
  'book': Book,
  'bookmark': Bookmark,
  'boot': Boot,
  'bow-tie': BowTie,
  'bowl': Bowl,
  'bowling': Bowling,
  'box': Box,
  'boxing-glove': BoxingGlove,
  'bracelet': Bracelet,
  'brain': Brain,
  'bread': Bread,
  'bridge': Bridge,
  'briefcase': Briefcase,
  'broccoli': Broccoli,
  'broom': Broom,
  'bucket': Bucket,
  'building': Building,
  'bus': Bus,
  'butterfly': Butterfly,
  'button': Button,
  'cabin': Cabin,
  'cable': Cable,
  'cactus': Cactus,
  'cake': Cake,
  'calculator': Calculator,
  'calendar': Calendar,
  'camera-off': CameraOff,
  'camera': Camera,
  'candle': Candle,
  'candlestick-chart': CandlestickChart,
  'candy': Candy,
  'cap': Cap,
  'capsule': Capsule,
  'car': Car,
  'carrot': Carrot,
  'cassette': Cassette,
  'cast': Cast,
  'castle': Castle,
  'cat': Cat,
  'caution': Caution,
  'cctv': Cctv,
  'certificate': Certificate,
  'chain': Chain,
  'chair': Chair,
  'chandelier': Chandelier,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'check': Check,
  'cheese': Cheese,
  'cherry': Cherry,
  'chess': Chess,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'chrome': Chrome,
  'church': Church,
  'circle': Circle,
  'clap': Clap,
  'clapperboard': Clapperboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clipboard': Clipboard,
  'clock': Clock,
  'cloud-drizzle': CloudDrizzle,
  'cloud-lightning': CloudLightning,
  'cloud-off': CloudOff,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud': Cloud,
  'clover': Clover,
  'cocktail': Cocktail,
  'code': Code,
  'codepen': Codepen,
  'codesandbox': Codesandbox,
  'coffee': Coffee,
  'coin': Coin,
  'coins': Coins,
  'columns': Columns,
  'comet': Comet,
  'command': Command,
  'compass': Compass,
  'cone': Cone,
  'cookie': Cookie,
  'copy': Copy,
  'copyright': Copyright,
  'corn': Corn,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  'corner-left-down': CornerLeftDown,
  'corner-left-up': CornerLeftUp,
  'corner-right-down': CornerRightDown,
  'corner-right-up': CornerRightUp,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'coupon': Coupon,
  'cow': Cow,
  'cpu': Cpu,
  'crab': Crab,
  'credit-card': CreditCard,
  'croissant': Croissant,
  'crop': Crop,
  'cross': Cross,
  'crosshair': Crosshair,
  'crowd': Crowd,
  'crown': Crown,
  'crutch': Crutch,
  'cube': Cube,
  'cupcake': Cupcake,
  'cylinder': Cylinder,
  'dartboard': Dartboard,
  'database': Database,
  'deer': Deer,
  'delete': Delete,
  'desk': Desk,
  'detective': Detective,
  'dewdrop': Dewdrop,
  'diamond': Diamond,
  'dice': Dice,
  'dinosaur': Dinosaur,
  'disc': Disc,
  'divide-circle': DivideCircle,
  'divide-square': DivideSquare,
  'divide': Divide,
  'dna': Dna,
  'dog': Dog,
  'dollar-sign': DollarSign,
  'dolphin': Dolphin,
  'donut': Donut,
  'door-open': DoorOpen,
  'door': Door,
  'dove': Dove,
  'download-cloud': DownloadCloud,
  'download': Download,
  'dragon': Dragon,
  'dress': Dress,
  'dribbble': Dribbble,
  'drill': Drill,
  'droplet': Droplet,
  'drum': Drum,
  'dumbbell': Dumbbell,
  'ear': Ear,
  'edit-2': Edit2,
  'edit-3': Edit3,
  'edit': Edit,
  'egg': Egg,
  'eggplant': Eggplant,
  'elephant': Elephant,
  'elevator': Elevator,
  'envelope-open': EnvelopeOpen,
  'envelope': Envelope,
  'equalizer': Equalizer,
  'eraser': Eraser,
  'euro': Euro,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  'eye': Eye,
  'facebook': Facebook,
  'factory': Factory,
  'family': Family,
  'fan': Fan,
  'fast-forward': FastForward,
  'fax': Fax,
  'feather': Feather,
  'fence': Fence,
  'ferris-wheel': FerrisWheel,
  'figma': Figma,
  'file-minus': FileMinus,
  'file-plus': FilePlus,
  'file-text': FileText,
  'file': File,
  'film': Film,
  'filter': Filter,
  'fingerprint': Fingerprint,
  'fire-truck': FireTruck,
  'fire': Fire,
  'fireplace': Fireplace,
  'firewall': Firewall,
  'first-aid': FirstAid,
  'fish': Fish,
  'fist': Fist,
  'flag': Flag,
  'flame': Flame,
  'flashlight': Flashlight,
  'flask': Flask,
  'floppy-disk': FloppyDisk,
  'flower': Flower,
  'flute': Flute,
  'fog': Fog,
  'folder-minus': FolderMinus,
  'folder-plus': FolderPlus,
  'folder': Folder,
  'football': Football,
  'footprint': Footprint,
  'fork': Fork,
  'fountain': Fountain,
  'fox': Fox,
  'framer': Framer,
  'fries': Fries,
  'frog': Frog,
  'frown': Frown,
  'fuel': Fuel,
  'galaxy': Galaxy,
  'gamepad': Gamepad,
  'garage': Garage,
  'gas-pump': GasPump,
  'gate': Gate,
  'gear': Gear,
  'gem': Gem,
  'gift-card': GiftCard,
  'gift': Gift,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'github': Github,
  'gitlab': Gitlab,
  'glasses': Glasses,
  'globe': Globe,
  'glove': Glove,
  'golf': Golf,
  'grape': Grape,
  'grid': Grid,
  'guitar': Guitar,
  'hamburger': Hamburger,
  'hammer': Hammer,
  'hand': Hand,
  'handbag': Handbag,
  'handshake': Handshake,
  'hard-drive': HardDrive,
  'hash': Hash,
  'hat': Hat,
  'haze': Haze,
  'headphones': Headphones,
  'headset': Headset,
  'heart-pulse': HeartPulse,
  'heart': Heart,
  'helicopter': Helicopter,
  'helmet': Helmet,
  'help-circle': HelpCircle,
  'heptagon': Heptagon,
  'hexagon': Hexagon,
  'highlighter': Highlighter,
  'hockey': Hockey,
  'home': Home,
  'hoodie': Hoodie,
  'horse': Horse,
  'hospital': Hospital,
  'hot-air-balloon': HotAirBalloon,
  'hotdog': Hotdog,
  'hotel': Hotel,
  'hourglass': Hourglass,
  'house': House,
  'ice-cream': IceCream,
  'icicle': Icicle,
  'id-card': IdCard,
  'igloo': Igloo,
  'image': Image,
  'inbox': Inbox,
  'incognito': Incognito,
  'infinity': Infinity,
  'info': Info,
  'instagram': Instagram,
  'invoice': Invoice,
  'iron': Iron,
  'italic': Italic,
  'jacket': Jacket,
  'jersey': Jersey,
  'joystick': Joystick,
  'juice': Juice,
  'kettlebell': Kettlebell,
  'key': Key,
  'keyboard': Keyboard,
  'keyhole': Keyhole,
  'knife': Knife,
  'ladder': Ladder,
  'ladybug': Ladybug,
  'lamp': Lamp,
  'lantern': Lantern,
  'layers': Layers,
  'layout': Layout,
  'leaf': Leaf,
  'lemon': Lemon,
  'library': Library,
  'life-buoy': LifeBuoy,
  'lightbulb': Lightbulb,
  'lighthouse': Lighthouse,
  'link-2': Link2,
  'link': Link,
  'linkedin': Linkedin,
  'lion': Lion,
  'lips': Lips,
  'list': List,
  'loader': Loader,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'lollipop': Lollipop,
  'lungs': Lungs,
  'magnet': Magnet,
  'mail': Mail,
  'mailbox': Mailbox,
  'map-pin': MapPin,
  'map': Map,
  'maple-leaf': MapleLeaf,
  'marker': Marker,
  'mask': Mask,
  'maximize-2': Maximize2,
  'maximize': Maximize,
  'medal': Medal,
  'meh': Meh,
  'menu': Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'meteor': Meteor,
  'metronome': Metronome,
  'mic-off': MicOff,
  'mic': Mic,
  'microchip': Microchip,
  'microphone-stage': MicrophoneStage,
  'microscope': Microscope,
  'microwave': Microwave,
  'milk': Milk,
  'minimize-2': Minimize2,
  'minimize': Minimize,
  'minus-circle': MinusCircle,
  'minus-square': MinusSquare,
  'minus': Minus,
  'mirror': Mirror,
  'modem': Modem,
  'monitor': Monitor,
  'monkey': Monkey,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'mosque': Mosque,
  'motorcycle': Motorcycle,
  'mountain': Mountain,
  'mouse-pointer': MousePointer,
  'move': Move,
  'mug': Mug,
  'museum': Museum,
  'mushroom': Mushroom,
  'music-note': MusicNote,
  'music': Music,
  'nail': Nail,
  'navigation-2': Navigation2,
  'navigation': Navigation,
  'necklace': Necklace,
  'no-entry': NoEntry,
  'nose': Nose,
  'notebook': Notebook,
  'notepad': Notepad,
  'octagon': Octagon,
  'octopus': Octopus,
  'omega': Omega,
  'oval': Oval,
  'oven': Oven,
  'owl': Owl,
  'package': Package,
  'padlock': Padlock,
  'paint-bucket': PaintBucket,
  'paint-roller': PaintRoller,
  'paintbrush': Paintbrush,
  'palm-tree': PalmTree,
  'panda': Panda,
  'pants': Pants,
  'paperclip': Paperclip,
  'parachute': Parachute,
  'paragraph': Paragraph,
  'parking': Parking,
  'pause-circle': PauseCircle,
  'pause': Pause,
  'paw': Paw,
  'peace-sign': PeaceSign,
  'pen-tool': PenTool,
  'pen': Pen,
  'pencil': Pencil,
  'penguin': Penguin,
  'pentagon': Pentagon,
  'pepper': Pepper,
  'percent': Percent,
  'person': Person,
  'phone-call': PhoneCall,
  'phone-forwarded': PhoneForwarded,
  'phone-incoming': PhoneIncoming,
  'phone-missed': PhoneMissed,
  'phone-off': PhoneOff,
  'phone-outgoing': PhoneOutgoing,
  'phone': Phone,
  'pi': Pi,
  'piano': Piano,
  'pie-chart': PieChart,
  'pig': Pig,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'pineapple': Pineapple,
  'pinecone': Pinecone,
  'pizza': Pizza,
  'plane': Plane,
  'planet': Planet,
  'plate': Plate,
  'play-circle': PlayCircle,
  'play': Play,
  'playlist': Playlist,
  'pliers': Pliers,
  'plug': Plug,
  'plus-circle': PlusCircle,
  'plus-square': PlusSquare,
  'plus': Plus,
  'pocket': Pocket,
  'podium': Podium,
  'popcorn': Popcorn,
  'pound': Pound,
  'power': Power,
  'presentation': Presentation,
  'pretzel': Pretzel,
  'price-tag': PriceTag,
  'printer': Printer,
  'profile': Profile,
  'prohibited': Prohibited,
  'projector': Projector,
  'pushpin': Pushpin,
  'puzzle': Puzzle,
  'pyramid': Pyramid,
  'qr-code': QrCode,
  'rabbit': Rabbit,
  'radar': Radar,
  'radiation': Radiation,
  'radio': Radio,
  'rainbow': Rainbow,
  'rake': Rake,
  'receipt': Receipt,
  'recycle': Recycle,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  'refrigerator': Refrigerator,
  'registered': Registered,
  'remote-control': RemoteControl,
  'repeat': Repeat,
  'rewind': Rewind,
  'rhombus': Rhombus,
  'ribbon': Ribbon,
  'ring': Ring,
  'road': Road,
  'rocket': Rocket,
  'rope': Rope,
  'rose': Rose,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'router': Router,
  'rss': Rss,
  'ruler': Ruler,
  'rupee': Rupee,
  'safe': Safe,
  'sailboat': Sailboat,
  'sandal': Sandal,
  'sandwich': Sandwich,
  'satellite-dish': SatelliteDish,
  'satellite': Satellite,
  'saturn': Saturn,
  'save': Save,
  'saw': Saw,
  'saxophone': Saxophone,
  'scale-balance': ScaleBalance,
  'scanner': Scanner,
  'scarf': Scarf,
  'school': School,
  'scissors': Scissors,
  'scooter': Scooter,
  'screw': Screw,
  'screwdriver': Screwdriver,
  'sd-card': SdCard,
  'search': Search,
  'seedling': Seedling,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'share-2': Share2,
  'share': Share,
  'sheep': Sheep,
  'shield-off': ShieldOff,
  'shield': Shield,
  'ship': Ship,
  'shirt': Shirt,
  'shoe': Shoe,
  'shooting-star': ShootingStar,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shovel': Shovel,
  'shrimp': Shrimp,
  'shuffle': Shuffle,
  'sidebar': Sidebar,
  'sigma': Sigma,
  'sim-card': SimCard,
  'siren': Siren,
  'skateboard': Skateboard,
  'skiing': Skiing,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'skyscraper': Skyscraper,
  'slack': Slack,
  'slash': Slash,
  'sliders': Sliders,
  'smartphone': Smartphone,
  'smile': Smile,
  'snail': Snail,
  'sneaker': Sneaker,
  'snowflake': Snowflake,
  'sock': Sock,
  'socket': Socket,
  'soda': Soda,
  'speaker': Speaker,
  'sphere': Sphere,
  'spider': Spider,
  'spiral': Spiral,
  'spoon': Spoon,
  'spray-can': SprayCan,
  'sprout': Sprout,
  'square': Square,
  'stadium': Stadium,
  'stairs': Stairs,
  'stamp': Stamp,
  'stapler': Stapler,
  'star': Star,
  'stethoscope': Stethoscope,
  'sticky-note': StickyNote,
  'stop-circle': StopCircle,
  'stopwatch': Stopwatch,
  'store': Store,
  'stove': Stove,
  'strawberry': Strawberry,
  'stroller': Stroller,
  'submarine': Submarine,
  'suitcase': Suitcase,
  'sun': Sun,
  'sunflower': Sunflower,
  'sunglasses': Sunglasses,
  'sunrise': Sunrise,
  'sunset': Sunset,
  'surfing': Surfing,
  'swimming': Swimming,
  'syringe': Syringe,
  't-shirt': TShirt,
  'table': Table,
  'tablet': Tablet,
  'tag': Tag,
  'target': Target,
  'taxi': Taxi,
  'tea': Tea,
  'teapot': Teapot,
  'tennis': Tennis,
  'tent': Tent,
  'terminal': Terminal,
  'test-tube': TestTube,
  'theater-masks': TheaterMasks,
  'thermometer': Thermometer,
  'thermostat': Thermostat,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'ticket': Ticket,
  'tie': Tie,
  'tiger': Tiger,
  'timer': Timer,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  'tomato': Tomato,
  'tool': Tool,
  'toolbox': Toolbox,
  'tooth': Tooth,
  'toothbrush': Toothbrush,
  'tornado': Tornado,
  'tractor': Tractor,
  'trademark': Trademark,
  'traffic-cone': TrafficCone,
  'traffic-light': TrafficLight,
  'trailer': Trailer,
  'train': Train,
  'tram': Tram,
  'trash-2': Trash2,
  'trash': Trash,
  'treadmill': Treadmill,
  'tree-evergreen': TreeEvergreen,
  'tree': Tree,
  'trello': Trello,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle': Triangle,
  'trophy': Trophy,
  'truck': Truck,
  'trumpet': Trumpet,
  'tulip': Tulip,
  'turtle': Turtle,
  'tv': Tv,
  'twitch': Twitch,
  'twitter': Twitter,
  'type': Type,
  'umbrella': Umbrella,
  'underline': Underline,
  'unicorn': Unicorn,
  'unlock': Unlock,
  'upload-cloud': UploadCloud,
  'upload': Upload,
  'usb': Usb,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-x': UserX,
  'user': User,
  'users': Users,
  'vacuum': Vacuum,
  'van': Van,
  'vault': Vault,
  'verified': Verified,
  'video-off': VideoOff,
  'video': Video,
  'vinyl': Vinyl,
  'violin': Violin,
  'virus': Virus,
  'voicemail': Voicemail,
  'volcano': Volcano,
  'volleyball': Volleyball,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'volume': Volume,
  'wallet': Wallet,
  'warehouse': Warehouse,
  'warning-triangle': WarningTriangle,
  'washing-machine': WashingMachine,
  'watch': Watch,
  'watermelon': Watermelon,
  'waves': Waves,
  'webcam': Webcam,
  'whale': Whale,
  'wheat': Wheat,
  'wheelchair': Wheelchair,
  'whistle': Whistle,
  'whiteboard': Whiteboard,
  'wifi-off': WifiOff,
  'wifi': Wifi,
  'wind': Wind,
  'windmill': Windmill,
  'wine': Wine,
  'wolf': Wolf,
  'worm': Worm,
  'wrench': Wrench,
  'x-circle': XCircle,
  'x-octagon': XOctagon,
  'x-ray': XRay,
  'x-square': XSquare,
  'x': X,
  'yen': Yen,
  'yoga': Yoga,
  'youtube': Youtube,
  'zap-off': ZapOff,
  'zap': Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
}
