// `fusionui theme` — scaffold a brand theme as a token-override file that
// compiles through @fusionui/tokens / createFusionUI. No component edits needed.
import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import prompts from 'prompts'
import { bold, cyan, green, red, dim } from 'kleur/colors'
import { normalizeHex } from './util.mjs'

const BRAND_KEYS = ['primary', 'secondary', 'success', 'danger', 'warning']

/**
 * Pure generator: given a partial palette, emit the brand theme module source.
 * Exported so it can be unit-tested without filesystem/prompt side effects.
 */
export function genThemeFile(colors, { name = 'brand', typescript = true } = {}) {
  const entries = BRAND_KEYS.filter(k => colors[k])
    .map(k => `      ${k}: '${colors[k]}',`)
    .join('\n')
  const typeImport = typescript ? `import type { ThemeDefinition } from '@fusionui/vue'\n` : ''
  const ann = typescript ? ': ThemeDefinition' : ''
  return `// Generated by \`fusionui theme\`. A brand theme = token overrides; no component
// source is touched. Pass this to createFusionUI({ theme: { themes: { ${name} } } }).
${typeImport}
export const ${name}Light${ann} = {
  dark: false,
  colors: {
${entries}
  },
}

export const ${name}Dark${ann} = {
  dark: true,
  colors: {
${entries}
  },
}
`
}

export async function runTheme(argv) {
  const onCancel = () => {
    console.log(red('✖ Cancelled'))
    process.exit(1)
  }
  const name = argv._[1] || argv.name || 'brand'
  const ts = argv.js ? false : true

  // Collect colors from flags (--primary=#xx120) or prompt for them.
  const colors = {}
  const missing = []
  for (const key of BRAND_KEYS) {
    const flag = argv[key]
    if (flag) {
      const hex = normalizeHex(flag)
      if (!hex) {
        console.log(red(`✖ --${key} "${flag}" is not a valid hex color`))
        process.exit(1)
      }
      colors[key] = hex
    } else {
      missing.push(key)
    }
  }

  if (missing.length && !argv.yes) {
    const answers = await prompts(
      missing.map(key => ({
        type: 'text',
        name: key,
        message: `${key} color (hex, blank to skip):`,
        initial: key === 'primary' ? '#195bff' : '',
      })),
      { onCancel }
    )
    for (const key of missing) {
      if (answers[key]) {
        const hex = normalizeHex(answers[key])
        if (!hex) {
          console.log(red(`✖ "${answers[key]}" is not a valid hex color`))
          process.exit(1)
        }
        colors[key] = hex
      }
    }
  }

  if (!Object.keys(colors).length) {
    console.log(red('✖ No colors provided. Pass --primary=#195bff or answer the prompts.'))
    process.exit(1)
  }

  const ext = ts ? 'ts' : 'js'
  const out = resolve(process.cwd(), argv.out || `fusionui.theme.${ext}`)
  if (existsSync(out) && !argv.force) {
    console.log(red(`✖ ${out} already exists. Pass --force to overwrite.`))
    process.exit(1)
  }
  writeFileSync(out, genThemeFile(colors, { name, typescript: ts }))

  console.log(`
${green('✔')} Wrote ${cyan(out)}

${bold('Wire it in')} where you call ${cyan('createFusionUI')}:

  ${dim(`import { ${name}Light, ${name}Dark } from './fusionui.theme'`)}
  ${dim('createFusionUI({')}
  ${dim(`  theme: { defaultTheme: '${name}Light', themes: { ${name}Light, ${name}Dark } },`)}
  ${dim('})')}
`)
}
