#!/usr/bin/env node
// Generates tree-shakeable icon modules from the raw Feather SVGs in ../svg.
//
//   node scripts/build-icons.mjs
//
// Output:
//   src/icons/<kebab>.ts   one createFeatherIcon() per icon
//   src/index.ts           re-exports every icon (PascalCase)
//   src/registry.ts        { 'kebab-name': Component } map for string lookup
//
// Deterministic (sorted) so diffs stay clean.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const svgDir = join(root, 'svg')
const iconsDir = join(root, 'src', 'icons')

function toPascal(name) {
  return name
    .split(/[^a-z0-9]+/i)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

/** Extracts the child nodes (tag + attributes) from a Feather SVG string. */
function parseNodes(svg) {
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '')
  const nodes = []
  const tagRe = /<([a-z]+)((?:\s+[\w-]+="[^"]*")*)\s*\/?>/gi
  let match
  while ((match = tagRe.exec(inner)) !== null) {
    const tag = match[1]
    if (tag === 'svg') continue
    const attrs = {}
    const attrRe = /([\w-]+)="([^"]*)"/g
    let attrMatch
    while ((attrMatch = attrRe.exec(match[2])) !== null) {
      attrs[attrMatch[1]] = attrMatch[2]
    }
    nodes.push([tag, attrs])
  }
  return nodes
}

function serializeNodes(nodes) {
  return nodes
    .map(([tag, attrs]) => {
      const attrStr = Object.entries(attrs)
        .map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`)
        .join(', ')
      return `  ['${tag}', { ${attrStr} }],`
    })
    .join('\n')
}

const files = readdirSync(svgDir)
  .filter(f => f.endsWith('.svg'))
  .sort()

rmSync(iconsDir, { recursive: true, force: true })
mkdirSync(iconsDir, { recursive: true })

const exports = []
const registry = []
const seenPascal = new Set()

for (const file of files) {
  const name = file.replace(/\.svg$/, '')
  const pascal = toPascal(name)
  const nodes = parseNodes(readFileSync(join(svgDir, file), 'utf8'))

  const module = `import { createFeatherIcon } from '../runtime'

export const ${pascal} = /*#__PURE__*/ createFeatherIcon('${name}', [
${serializeNodes(nodes)}
])
`
  writeFileSync(join(iconsDir, `${name}.ts`), module)
  // A handful of distinct kebab names collapse to the same PascalCase (e.g.
  // `arrow-down-0-1` and `arrow-down-01`, which Lucide keeps as duplicate
  // aliases of one icon). The kebab name is the unique key, so the string
  // registry keeps every one; the named export can only carry a Pascal once, so
  // emit it for the first and let the alias resolve through the registry.
  if (!seenPascal.has(pascal)) {
    seenPascal.add(pascal)
    exports.push(`export { ${pascal} } from './icons/${name}'`)
  }
  // Import under a unique local binding so colliding Pascals don't clash here.
  const local = 'I_' + name.replace(/[^a-z0-9]+/gi, '_')
  registry.push({ name, pascal, local })
}

const banner = '// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.\n\n'

writeFileSync(
  join(root, 'src', 'index.ts'),
  banner +
    `export * from './runtime'\n` +
    `export { featherSet } from './set'\n` +
    `export { featherAliases } from './aliases'\n` +
    `export { featherIcons, iconNames } from './registry'\n` +
    `export { iconTags } from './tags'\n` +
    `// Brand-forward aliases — this is the FusionUI icon set.\n` +
    `export { featherSet as fusionSet } from './set'\n` +
    `export { featherAliases as fusionAliases } from './aliases'\n` +
    `export { featherIcons as fusionIcons } from './registry'\n` +
    exports.join('\n') +
    '\n'
)

writeFileSync(
  join(root, 'src', 'registry.ts'),
  banner +
    registry.map(r => `import { ${r.pascal} as ${r.local} } from './icons/${r.name}'`).join('\n') +
    `\n\nimport type { FeatherIcon } from './runtime'\n\n` +
    `export const featherIcons: Record<string, FeatherIcon> = {\n` +
    registry.map(r => `  '${r.name}': ${r.local},`).join('\n') +
    `\n}\n\n` +
    `/** Every icon name (kebab-case), in sorted order. */\n` +
    `export const iconNames: string[] = Object.keys(featherIcons)\n`
)

console.log(`Generated ${files.length} FusionUI icon modules + index + registry.`)
