#!/usr/bin/env node
// One-shot importer that folds the Lucide icon set into svg/.
//
//   node scripts/import-lucide.mjs
//
// Rules (decided with the maintainer):
//   - For every name Lucide draws, Lucide's drawing wins. Lucide is a Feather
//     fork with the same conventions (24×24, stroke 2, round caps, currentColor),
//     and its drawings are cleaner than the hand-rolled "extended" ones that had
//     accreted here — so overwriting is an upgrade, not a regression.
//   - Names Lucide does NOT have (our bespoke icons: acorn, avocado, bee, …) are
//     left exactly as they are. Nothing is removed, so no `icon="…"` name breaks.
//
// It also emits src/tags.json — Lucide's synonym lists (trash → bin, delete,
// garbage, …) — so the docs search can match on meaning, not just substring.
//
// Lucide is ISC licensed (see NOTICE). This script is dev-only and never ships.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { createRequire } from 'node:module'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const svgDir = join(root, 'svg')
const require = createRequire(import.meta.url)

const lucideDir = dirname(require.resolve('lucide-static/package.json'))
const lucideIcons = join(lucideDir, 'icons')
const lucideTags = JSON.parse(readFileSync(join(lucideDir, 'tags.json'), 'utf8'))

// Canonical single-line form matching the existing svg/ files, so raw-SVG
// consumers and git diffs stay consistent. The root attrs mirror the runtime's
// SVG_BASE; per-node attributes (a handful of Lucide icons override stroke-width
// or fill) are preserved verbatim.
function canonicalize(name, raw) {
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s+/g, ' ')
    .trim()
  const head =
    `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" ` +
    `fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" ` +
    `stroke-linejoin="round" class="feather feather-${name}">`
  return `${head}${inner}</svg>\n`
}

const before = new Set(readdirSync(svgDir).filter(f => f.endsWith('.svg')))

let overwritten = 0
let added = 0
for (const file of readdirSync(lucideIcons).filter(f => f.endsWith('.svg'))) {
  const name = file.replace(/\.svg$/, '')
  const out = canonicalize(name, readFileSync(join(lucideIcons, file), 'utf8'))
  if (before.has(file)) overwritten++
  else added++
  writeFileSync(join(svgDir, file), out)
}

const kept = [...before].filter(f => {
  const name = f.replace(/\.svg$/, '')
  return !readdirSync(lucideIcons).includes(`${name}.svg`)
})

// Trim tags to icons we actually ship, and drop tags that merely repeat the name.
const names = new Set(
  readdirSync(svgDir)
    .filter(f => f.endsWith('.svg'))
    .map(f => f.replace(/\.svg$/, ''))
)
const tags = {}
for (const [name, list] of Object.entries(lucideTags)) {
  if (!names.has(name)) continue
  const cleaned = [...new Set(list.map(t => String(t).toLowerCase().trim()))].filter(
    t => t && t !== name && !name.includes(t)
  )
  if (cleaned.length) tags[name] = cleaned
}
writeFileSync(
  join(root, 'src', 'tags.ts'),
  `// AUTO-GENERATED by scripts/import-lucide.mjs — do not edit by hand.\n` +
    `// Search synonyms sourced from Lucide (ISC — see NOTICE), trimmed to the\n` +
    `// icons this package ships and stripped of tags that just repeat the name.\n\n` +
    `export const iconTags: Record<string, string[]> = ${JSON.stringify(tags)}\n`
)

const total = names.size
console.log(`Lucide import complete.`)
console.log(`  overwritten (Lucide's drawing wins) : ${overwritten}`)
console.log(`  added (new to the set)              : ${added}`)
console.log(`  kept (bespoke, not in Lucide)       : ${kept.length}`)
console.log(`  total icons now                     : ${total}`)
console.log(`  search tags emitted for             : ${Object.keys(tags).length} icons`)
